from aiogremlin.driver import pool as pool
from typing import Any

class GremlinServer:

    def __init__(self, url: Any, loop: Any, **config: Any) -> None: ...

    @property
    def url(self): ...

    @property
    def pool(self): ...

    async def close(self) -> None: ...

    async def get_connection(self): ...

    async def initialize(self) -> None: ...

    @classmethod
    async def open(cls, url: Any, loop: Any, **config: Any): ...
