sudo: required
dist: trusty

language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

services:
  - docker

before_install:
  - docker pull leifurhauks/gremlin-server-tinkergraph

install:
  - pip install -e .[all]
  - docker run -d --name gst -p 8182:8182 leifurhauks/gremlin-server-tinkergraph

before_script:
  - sleep 30

script:
  - python setup.py test

after_success:
  - coveralls
