from gremlin_python.driver import transport
from typing import Any, Optional

class AiohttpTransport(transport.AbstractBaseTransport):

    def __init__(self, loop: Any) -> None: ...

    async def connect(self, url: Any, *, ssl_context: Optional[Any] = ...) -> None: ...

    async def write(self, message: Any) -> None: ...

    async def read(self): ...

    async def close(self) -> None: ...

    @property
    def closed(self): ...
