from typing import Any

class ConfigError(Exception): ...

class ClientError(Exception): ...

class MappingError(Exception): ...

class ValidationError(Exception): ...

class ElementError(Exception): ...

class ConfigurationError(Exception): ...

class GremlinServerError(Exception):
    status_code: Any = ...
    msg: Any = ...

    def __init__(self, status_code: Any, msg: Any) -> None: ...

class ResponseTimeoutError(Exception): ...
